export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  rbenv
  ruby
  thor
  bundler
  rails
  lein
)

source "$ZSH/oh-my-zsh.sh"
source "$HOME/dotfiles/brew/aliases.sh"
source "$HOME/dotfiles/docker/aliases.sh"
source "$HOME/dotfiles/git/aliases.sh"
#source "$HOME/dotfiles/terraform/aliases.sh"
#source "$HOME/dotfiles/java/aliases.sh"

source "$HOME/dotfiles/ruby/rbenv-init.sh"

# Vault autocomplete
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/vault vault

# History and syntax highlighting
# Must be at the end of the zshrc
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

