export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  rbenv
  ruby
  thor
  bundler
  rails
  lein
)

source $ZSH/oh-my-zsh.sh

# Docker
alias dup='docker-compose up --detach'
alias dupb='docker-compose up --detach --build'
alias ddown='docker-compose down --volumes'
alias dd='docker-compose down --volumes'
alias dcleanv='docker volume rm $(docker volume ls -q --filter=dangling=true)'
alias dcleani='docker rmi $(docker images -a --filter=dangling=true -q)'
alias dcleanc='docker rm $(docker ps --filter=status=exited --filter=status=created -q)'
alias dclean='dcleanv; dcleani'
alias dkill='docker kill $(docker ps -q)'
alias docker-reset-containers='docker rm -f $(docker ps -a -q)'
alias docker-reset-images='docker rmi -f $(docker images -q)'
alias docker-reset='docker-reset-containers; docker-reset-images'

# Vault autocomplete
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/vault vault

# Must be at the end of the file
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

